name: Collect electricity load

on:
  schedule:
    - cron: '0 0 15 * *'  # 15th of every month 0:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      NEON_DB: ${{ secrets.NEON_DB }}
      PYTHONPATH: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python get_data/fetch_generation.py
          python get_data/fetch_embedded_generation.py
          python get_data/fetch_grid_export.py
          python get_data/fetch_grid_import.py
